kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: eco
  name: eco-server
  labels:
    app: eco-server

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eco-server
  template:
    metadata:
      labels:
        app: eco-server
    spec:
      volumes:
        - name: server-config
          persistentVolumeClaim:
            claimName: server-config
        - name: server-storage
          persistentVolumeClaim:
            claimName: server-storage
      imagePullSecrets:
        - name: oechsler
      initContainers:
        - name: server-config-perm
          image: alpine:latest
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
          - name: server-config
            mountPath: /data
        - name: server-storage-perm
          image: alpine:latest
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
          - name: server-storage
            mountPath: /data
      containers:
        - name: files
          image: registry.digitalocean.com/oechsler/files:latest
          resources:
            requests:
              cpu: 32m
              memory: 32Mi
            limits:
              cpu: 32m
              memory: 32Mi
          env:
            - name: GROUP_ID
              value: "1000"
            - name: USER_ID
              value: "1000"
          volumeMounts:
            - mountPath: "/data/mounts/config"
              name: server-config
            - mountPath: "/data/mounts/storage"
              name: server-storage
          ports:
            - name: sftp
              containerPort: 22
        - name: server
          image: strangeloopgames/eco-game-server
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 2.5Gi
          volumeMounts:
            - mountPath: "/app/Configs"
              name: server-config
            - mountPath: "/app/Storage"
              name: server-storage
          ports:
            - name: eco
              containerPort: 3000
              protocol: UDP
            - name: http
              containerPort: 3001
          startupProbe:
            initialDelaySeconds: 120
            periodSeconds: 10
            httpGet:
              path: /
              port: 3001
              
