kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: eco
  name: eco-files
  labels:
    app: eco-files

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: eco-files
  template:
    metadata:
      labels:
        app: eco-files
    spec:
      volumes:
        - name: server-storage
          persistentVolumeClaim:
            claimName: server-storage
      containers:
        - name: files
          image: oechsler.azurecr.io/files:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: GROUP_ID
              value: "1"
            - name: USER_ID
              value: "1"
          volumeMounts:
            - mountPath: "/data/mounts/storage"
              name: server-storage
          ports:
            - name: sftp
              containerPort: 22
              
