apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-database

spec:
  ports:
    - protocol: TCP
      name: mysql-tcp
      port: 3306
  selector:
    app: wordpress-database
---

apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-database-admin

spec:
  ports:
    - protocol: TCP
      name: phpmyadmin-http
      port: 80
  selector:
    app: wordpress-database-admin
---

apiVersion: v1
kind: Service
metadata:
  namespace: wordpress
  name: wordpress-instance

spec:
  ports:
    - protocol: TCP
      name: wordpress-http
      port: 80
  selector:
    app: wordpress-instance